name: "Build Check"
on: 
    push: 
      branches: ["main"]
jobs: 
  # Install Environment
  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        # https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - run: npm ci
      - run: npm lint
      - run: npm build
